build_and_deploy_job:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Upload Static Content
      uses: azure/static-web-apps-deploy@v1
      with:
        app_location: "/"   # Diretório do código-fonte (onde está index.html)
        output_location: ""  # Deixe vazio para desativar build
