name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Define que o deploy acontece quando houver push na branch main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Static Content
        uses: azure/static-web-apps-deploy@v1
        with:
          app_location: "/"   # Diretório do código-fonte
          output_location: ""  # Sem build, pois é um site estático
